<a href="https://colab.research.google.com/github/HRKhan-DS/deep_learning_pytorch/blob/main/deep_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
torch.__version__

'2.4.1+cu121'

# **TENSORS**
A torch.tensor is a multi-dimensionsnal matrix containing elements of single data type.
Similar to numpy arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).
default data type of float32.
More suitable for deep learning than a numpy array.

# **LISTS**

In [ ]:
my_list = [[1,2,3,4,5],[6,7,8,9,10],[0,1,2,5]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [0, 1, 2, 5]]

# **Nummpy Arrays**

In [ ]:
np1 = np.random.rand(3,4)
np1

array([[0.18236804, 0.6214722 , 0.56516554, 0.43971294],
       [0.29021689, 0.79837314, 0.64220232, 0.52281987],
       [0.72421176, 0.10154431, 0.28479403, 0.8743308 ]])

In [ ]:
np1.dtype

dtype('float64')

# **Tensors**

In [ ]:
tensor_2d = torch.rand(3,4)
print(tensor_2d)
print(tensor_2d.ndim)
print(tensor_2d.shape)
print(tensor_2d.dtype)
print(tensor_2d.device)

tensor([[0.4122, 0.9841, 0.3465, 0.8987],
        [0.2029, 0.3849, 0.0227, 0.6738],
        [0.4204, 0.8307, 0.7322, 0.1647]])
2
torch.Size([3, 4])
torch.float32
cpu


In [ ]:
tensor_3d = torch.rand(3,4,1)
print(tensor_3d)
print(tensor_3d.ndim)
print(tensor_3d.shape)

tensor([[[0.5809],
         [0.7331],
         [0.9044],
         [0.7713]],

        [[0.5555],
         [0.7405],
         [0.6090],
         [0.6835]],

        [[0.4797],
         [0.9241],
         [0.3374],
         [0.1201]]])
3
torch.Size([3, 4, 1])


In [ ]:
my_tensor = torch.tensor(np1)
print(my_tensor)
print(my_tensor.ndim)
print(my_tensor.shape)

tensor([[0.1824, 0.6215, 0.5652, 0.4397],
        [0.2902, 0.7984, 0.6422, 0.5228],
        [0.7242, 0.1015, 0.2848, 0.8743]], dtype=torch.float64)
2
torch.Size([3, 4])


In [ ]:
tensor_0d = torch.tensor(42)
print(tensor_0d)
print(tensor_0d.ndim)
print(tensor_0d.shape)
print(tensor_0d.item())

tensor(42)
0
torch.Size([])
42


In [ ]:
tensor_1d = torch.tensor([2,3,4])
print(tensor_1d)
print(tensor_1d.ndim)
print(tensor_1d.shape)
# print(tensor_1d.item()) a Tensor with 3 elements cannot be converted to Scalar

tensor([2, 3, 4])
1
torch.Size([3])


In [ ]:
tensor_2d = torch.tensor([[2,3,4],[0,1,3]])
print(tensor_2d)
print(tensor_2d.ndim)
print(tensor_2d.shape)

tensor([[2, 3, 4],
        [0, 1, 3]])
2
torch.Size([2, 3])


In [ ]:
tensor_2d = torch.rand(3,4)
print(tensor_2d)
print(tensor_2d.ndim)
print(tensor_2d.shape)

tensor([[0.5272, 0.7622, 0.6744, 0.6876],
        [0.1199, 0.0184, 0.8571, 0.5583],
        [0.3545, 0.1108, 0.9961, 0.1228]])
2
torch.Size([3, 4])


# Tensor OPS

In [ ]:
import torch

In [ ]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Reshape and View

In [ ]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch2 = my_torch2.reshape(2,-1)  # when not know the total elemet use -1
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

view(): Restrictive – Requires contiguous memory and shares data without copying.
reshape(): Flexible – Works with non-contiguous tensors and may copy data if needed.

In [ ]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch6=my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch8=my_torch7.reshape(2,5)
my_torch8

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch7[1] = 51
my_torch7

tensor([ 0, 51,  2,  3,  4, 51, 51, 51, 51, 51])

In [ ]:
my_torch8

tensor([[ 0, 51,  2,  3,  4],
        [51, 51, 51, 51, 51]])

# slices

In [ ]:
my_torch9 = torch.arange(10)
my_torch9

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch9[7]

tensor(7)

In [ ]:
my_torch10 = my_torch9.reshape(5,2)
my_torch10

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
my_torch10[:,1]

tensor([1, 3, 5, 7, 9])

In [ ]:
# return column
my_torch10[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])